print("Hello world")
print("Khit")
print("read novel")
print("My favorite music genre is Jazz.")
print("Student")
print("Soccer")
print("My favorite music genre is Jazz.")
print("I like to drink coconut water.")
